- name: Querying v$database
  antony_with_no_h.oracle.table_dictionary:
    database_name: "{{ sid | d(inventory_hostname) }}"
    table_name: v$database
  register: v_database
  
- name: Enable archive logging
  antony_with_no_h.oracle.sqlplus:
    database_name: "{{ sid | d(inventory_hostname) }}"
    sql: |
      CONN / AS SYSDBA
      SHUT IMMEDIATE;
      STARTUP MOUNT;
      ALTER DATABASE NOARCHIVELOG;
      ALTER DATABASE OPEN;
  when: "v_database.resultset.LOG_MODE == 'ARCHIVELOG'"